### PR TITLE
Fix python tables generation on Bazel 8

### PR DESCRIPTION
**Pull request by tomrenn**
This is aimed at fixing https://github.com/google/perfetto/issues/1299

Previously, build targets like `@perfetto//:src_trace_processor_tables_tables_python_gen` worked because somewhere on the python path was `external/perfetto/src/trace_processor/tables/`, but when starting to use Bazel 8, this `external/perfetto/.*` prefix is no longer available. The python path has `src/trace_processor/tables` available on it.

Instead of trying to fiddle with relative paths and try to identify the repo_name inside starlark, this change modifies the --inputs parameter to pass the modules names directly.

### CODE REVIEW

**Comment by tomrenn** [comment]
It looks like builds are failing due to 

AttributeError: 'str' object has no attribute 'removesuffix'

removesuffix was added in python 3.9 - I wonder if it's possible to update the python version on CI? Otherwise I can move that logic to a helper method

**Comment by LalitMaganti** [comment]
We need to stick with Python 3.8 for now until it hits EOL.

**Comment by tomrenn** [comment]
Ack, I updated the commit so that it works on python 3.8. Thanks for the quick review!

**Review by LalitMaganti — APPROVED** [review]
