### ISSUE TITLE
Perfetto→Chromium autoroller is broken

### ISSUE THREAD

**Issue by petrcermak** [google/perfetto#2634]
Sample failing CL: https://chromium-review.googlesource.com/c/chromium/src/+/6862786?tab=checks

Error:

```
[10176/98541] CXX clang_x64_v8_arm64/obj/third_party/perfetto/src/base/base/rt_mutex.o
../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF clang_x64_v8_arm64/obj/third_party/perfetto/src/base/base/rt_mutex.o.d -D__S...(too long)
In file included from ../../third_party/perfetto/src/base/rt_mutex.cc:17:
../../third_party/perfetto/include/perfetto/ext/base/rt_mutex.h:214:7: error: no matching 'operator new' function for non-allocating placement new expression; include 
  214 |       new (&storage_) RtMutex();
      |       ^   ~~~~~~~~~~~
../../third_party/perfetto/include/perfetto/ext/base/rt_mutex.h:216:7: error: no matching 'operator new' function for non-allocating placement new expression; include 
  216 |       new (&storage_) std::mutex();
      |       ^   ~~~~~~~~~~~
2 errors generated.
remote-exec d77d4bbac7f180f5aee3c72ce55b6f98d7b3324b83b4f13d7a19b44dcc0af3ba/355 failed: exit=1
```

Based on the error message and list of commits in the CL above, I strongly suspect #1648 is the cause.

@primiano Can you please revert the commit or fix forward 🙏 ?

**Comment by JoeNotCharlesGoogle** [comment]
Interesting, I got a different error message, also caused by [#1648](https://github.com/google/perfetto/pull/1648):

```
In file included from ../../third_party/perfetto/src/base/rt_mutex.cc:17:
../../third_party/perfetto/include/perfetto/ext/base/rt_mutex.h:234:3: error: mutex 'std_mutex()' is not held on every path through here [-Werror,-Wthread-safety-analysis]
  234 |   }
      |   ^
../../third_party/perfetto/include/perfetto/ext/base/rt_mutex.h:232:20: note: mutex acquired here
  232 |       std_mutex()->lock();
      |                    ^
../../third_party/perfetto/include/perfetto/ext/base/rt_mutex.h:240:20: error: releasing mutex 'std_mutex()' that was not held [-Werror,-Wthread-safety-analysis]
  240 |       std_mutex()->unlock();
      |                    ^
2 errors generated.
```

However, the autoroller is passing now (first success: https://crrev.com/c/6865329). It looks like both errors were fixed by [#2619](https://github.com/google/perfetto/pull/2619).
