### ISSUE TITLE
MSVC_2019: ScopedEvent: attempting to reference a deleted function

### ISSUE THREAD

**Issue by mlappo** [google/perfetto#407]
This is a regression when updating from v30.0 to v31.0.

Previously compiled code is breaking compilation with:
```
error C2280: '<someclass>::Read::ScopedEvent57::EventFinalizer::EventFinalizer(<someclass>::Read::ScopedEvent57::EventFinalizer &&)': attempting to reference a deleted function
<somepath>(57): note: see declaration of '<someclass>::Read::ScopedEvent57::EventFinalizer::EventFinalizer'
<somepath>(57): note: '<someclass>::Read::ScopedEvent57::EventFinalizer::EventFinalizer(<someclass>::Read::ScopedEvent57::EventFinalizer &&)': function was explicitly deleted
```

**Comment by LalitMaganti** [comment]
Thanks for reporting. Fixed by https://android-review.git.corp.google.com/c/platform/external/perfetto/+/2355222

**Comment by mlappo** [comment]
Nice! Unfortunately I can't see the patch from outside... Is it already synced to github?

**Comment by LalitMaganti** [comment]
Sorry updated the URL (we changed how URLs work so I cannot just copy paste links from the address bar :( )

The fix has not landed but should do so soon.

**Comment by mlappo** [comment]
Thanks a lot! This was quick :-) Do you plan to release a new version with the fix?

**Comment by LalitMaganti** [comment]
We're overdue on the December release at this point and given people are going to be out for Christmas, we may just skip this release and do one for v32 in January.

**Comment by miklelappo** [comment]
Sounds good! I'll add an official patch to conan recipe until then.

**Comment by mlappo** [comment]
Closed as fixed.
